# System-setup for the server
{
  flake.modules.nixos.home-server =
    { pkgs, config, ... }:
    let
      inherit (config.custom) mainUser;
    in
    {
      # ---------------------------------------------------------------
      # IMPORTANT SETTINGS
      # ---------------------------------------------------------------
      # Allows rebuilding with '--target-host' from main laptop
      nix.settings.trusted-users = [ mainUser ];

      # Allows connecting to server over SSH
      services.openssh.enable = true;

      # Allows connecting server to wifi (needed if server does not have an ethernet-port)
      networking.networkmanager.enable = true;

      # Setup user with a password, otherwise cannot login. Can alternatively use 'initialPassword' and enable 'mutableUsers', but would then need to add the password-file generated by `passwd` to persistent storage
      users.mutableUsers = false;
      users.users.${mainUser} = {
        isNormalUser = true;
        hashedPassword = "$6$l4qRlTctBwRHhqCh$w2OH3O..z0sim7rYhm/1MeUtmiIxA2G2b.K7rtPBjkazlL6VwbbzDD.aek55veKOcS2dGeBHAzlIwwW6BCyPR0";
        extraGroups = [
          "wheel"
          "networkmanager"
        ];
        openssh.authorizedKeys.keys = [
          # Asus21 user-key
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID2I6rQN0INm8Y4lajgTzgTZdBX1U/9NdiqtZ3xYjwoj"

        ];
      };

      # Wont boot if lost on reinstall
      boot.loader.systemd-boot.enable = true;

      # ---------------------------------------------------------------
      # Other settings
      # ---------------------------------------------------------------
      boot.loader.efi.canTouchEfiVariables = true;
      boot.kernelParams = [ "consoleblank=60" ];

      networking.firewall.enable = true;
      networking.firewall.allowedTCPPorts = [ 22 ]; # SSH only for now, add more as services enabled

      time.timeZone = "Europe/Copenhagen";
      i18n.defaultLocale = "en_US.UTF-8";
      console.keyMap = "dk";

      # Some basic tools, ensuring ability to fix stuff
      environment.systemPackages = with pkgs; [
        vim
        neovim
        helix
        git

        tree # List all of directory
      ];

      services.openssh.settings = {
        PermitRootLogin = "no";
        # IMPORTANT: With this set, losing authorized keys means being locked out
        PasswordAuthentication = false;
      };

      ### Battery saving optimizations
      hardware.bluetooth.enable = false;
      powerManagement = {
        enable = true;
        cpuFreqGovernor = "powersave";
      };
      services.logind.settings = {
        Login.HandleLidSwitchExternalPower = "ignore";
        Login.HandleLidSwitch = "ignore";
      };
      systemd.sleep.settings.Sleep = {
        AllowSuspend = "no";
        AllowHibernation = "no";
        AllowSleep = "no";
      };
      services.tlp.enable = true;

      # Won't work on surface-pro, but maybe on a future server
      services.tlp.settings = {
        START_CHARGE_THRESH_BAT0 = 40;
        STOP_CHARGE_THRESH_BAT0 = 80;
      };
    };
}
