# NOTEBOOK SETTINGS
[notebook]
# Default notebook
dir = "~/JD/00-09_Meta/03_Program-data/zk"

[note]
language = "da"

[extra]
author = "Thomas H. Surlykke"


[group.zettlekasten]
paths = ["zettlekasten"]
[group.zettlekasten.note]
filename = "{{id}}-{{slug title}}"

[group.reference]
paths = ["reference"]
[group.reference.note]
filename = "{{slug title}}"


[alias]
# r = 'zk new reference -t "$@"'
r = 'zk edit reference -i "$@"'
# z = 'zk new zettlekasten -t "$@"'
z = 'zk edit zettlekasten -i "$@"'
conf = '$EDITOR ~/.dotfiles/zk/config.toml'
paths = "zk list --quiet --format \"'{{path}}'\" --delimiter ' ' --no-pager -m $@"
inline = 'zk list --quiet --format {{path}} --delimiter ,  --working-dir=$ZK_NOTEBOOK_DIR/zettlekasten "$@"'
to = 'zk list --link-to "`zk inline $@`"'

fzf-preview = "bat -p --color always {-1}"

[tool]
shell = "zsh"
