# xwayland dpi scale
exec-once=echo "Xft.dpi: 140" | xrdb -merge

# dms shell
exec-once=QT_WAYLAND_FORCE_DPI=96 noctalia-shell

# keep clipboard content
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0

# clipboard content manager
exec-once=wl-paste --type text --watch cliphist store
