# xwayland dpi scale
# exec-once=echo "Xft.dpi: 144" | xrdb -merge

exec-once=noctalia-shell

# keep clipboard content
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0

# clipboard content manager
exec-once=wl-paste --type text --watch cliphist store
