# To let DMS start through systemd
# TODO: Look into whether this can be moved to nixos-config
exec-once=dbus-update-activation-environment --systemd --all
exec-once=systemctl --user start mango-session.target

# Start xwayland
exec-once=xwayland-satellite :11 & sleep 0.5s && echo "Xft.dpi: 140" | xrdb -merge
