# Monitor Rules
# monitorrule=name:eDP-1,width:1920,height:1080,refresh:60,x:0,y:10,scale:1,vrr:0,rr:0

### Surface book
# NOTE: Adding 'model:' does not seem to work.
# monitorrule=name:eDP-1,make:Panasonic Industry Company,serial:0x05A11100,width:3000,height:2000,refresh:60,x:0,y:10,scale:1.5,vrr:0,rr:0

# External monitor
monitorrule=name:^DP-1,x:0,y:0
# Laptop
monitorrule=name:^eDP-1,x:3840,y:540
